package jp.mydns.sys1yagi.android.greendaosample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jp.mydns.sys1yagi.android.greendaosample.Todo;

import jp.mydns.sys1yagi.android.greendaosample.TodoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoDaoConfig;

    private final TodoDao todoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        todoDao = new TodoDao(todoDaoConfig, this);

        registerDao(Todo.class, todoDao);
    }
    
    public void clear() {
        todoDaoConfig.getIdentityScope().clear();
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

}
